// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// القيم من متغيرات البيئة (.env) — مع fallback للقيم الافتراضية
const SUPABASE_URL =
  import.meta.env.VITE_SUPABASE_URL ||
  "https://wgolkcztdrwdphwjvqxt.supabase.co";

const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indnb2xrY3p0ZHJ3ZHBod2p2cXh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU2MDcwOTYsImV4cCI6MjA4MTE4MzA5Nn0.d71qwqbrpRlBv502ShvhxZWfrmwQI6yWLdSZlaLhtzo";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    // تجاوز navigator.locks الذي قد يعلق إذا بقي قفل قديم من تبويب سابق
    // lockNoOp: ينفذ العملية مباشرة بدون قفل — آمن لتطبيق تبويب واحد
    lock: async (name: string, acquireTimeout: number, fn: () => Promise<any>) => {
      return await fn();
    },
  },
  // إعدادات Realtime محسّنة للعمل داخل Capacitor (WebSocket keepalive)
  realtime: {
    params: {
      eventsPerSecond: 10,
    },
    heartbeatIntervalMs: 15000,   // نبضة كل 15 ثانية للحفاظ على الاتصال
    reconnectAfterMs: (tries: number) => {
      // إعادة الاتصال سريعاً: 0.5s, 1s, 2s, 4s, max 10s
      return Math.min(500 * Math.pow(2, tries), 10000);
    },
  },
  // Add error handling and logging
  global: {
    headers: {
      'X-Client-Info': 'raan-captain-app',
    },
  },
});